export const strings = {
  it: {
    appName: "PixelCraft Academy",
    missionTitle: "Insegna a EDO a riconoscere i miei disegni",
    fakeProfile: "Allievo",
    labels: {
      cat: "GATTO",
      house: "CASA",
      catShort: "gatto",
      houseShort: "casa",
    },
    edo: {
      welcome: "Ciao! Sono EDO. Insegnami i disegni.",
      intro: "Mostrami gatti e case.",
      needCat: "Mi servono altri gatti.",
      needHouse: "Mi servono altre case.",
      ready: "Ho abbastanza esempi. Addestrami!",
      studying: "Studio i tuoi disegni.",
      trained: "Adesso provo a riconoscere.",
      lowConf: "Non sono sicuro… ho visto pochi disegni. Me ne fai vedere altri?",
      highConf: "Ho visto molti più disegni. Riproviamo.",
      guessCat: "Secondo me è un gatto.",
      guessHouse: "Secondo me è una casa.",
      thanks: "Grazie. Imparo da te.",
      cameraNeed: "Mi serve la fotocamera per vedere.",
      drawHint: "Disegna con il dito.",
      learnNow: "Va bene. Lo imparo adesso.",
      addMore: "Ancora qualche disegno, poi riprovo.",
      enough: "Ho gia' tanti disegni di questo tipo.",
      unfamiliar: "Non ho mai visto niente di simile.",
      split: "Alcuni disegni dicono una cosa, altri un'altra.",
      askMore: "Fammene vedere altri e ci riprovo.",
      sameDrawing: "Questo l'ho gia' visto. Provane uno nuovo.",
      star1: "Prima stella! Ho imparato un po'.",
      star2: "Seconda stella! Più esempi aiutano.",
      star3: "Terza stella! Disegno nuovo riconosciuto.",
      lessonIntro: "Ora ti spiego i dati.",
      noCamera: "Niente fotocamera. Scatta o disegna.",
      looking: "Guardo il disegno…",
      complete: "Missione finita. Sei tu l'insegnante.",
    },
    ui: {
      start: "Inizia",
      continue: "Continua",
      back: "Indietro",
      train: "Addestra",
      retrain: "Addestra di nuovo",
      test: "Prova EDO",
      addDrawings: "Aggiungi disegni",
      photograph: "Fotografa",
      draw: "Disegna",
      sample: "Disegno di prova",
      save: "Salva",
      cancel: "Annulla",
      clear: "Cancella",
      shutter: "Scatta",
      cameraOk: "Va bene",
      yesCat: "Sì, è un GATTO",
      yesHouse: "Sì, è una CASA",
      noCat: "No, è un GATTO",
      noHouse: "No, è una CASA",
      seeLesson: "Perché i dati sono importanti",
      finish: "Ho capito",
      speak: "Ascolta EDO",
      countOf: "di",
      loading: "EDO si prepara…",
      pickLabel: "Tocca GATTO o CASA, poi aggiungi un disegno.",
      needThree: "Servono almeno 3 gatti e 3 case.",
      goalTen: "Arriviamo a 10 per ciascuno.",
      permissionBody:
        "EDO ha bisogno della fotocamera per vedere i tuoi disegni. Le foto restano sul telefono.",
      emptyCat: "Nessun gatto ancora",
      emptyHouse: "Nessuna casa ancora",
      testHint: "Mostra un disegno. EDO prova a dire che cos'è.",
      newDrawing: "Usa un disegno nuovo, mai fotografato.",
      bootError: "Non riesco a caricare il cervello di EDO. Ricarica la pagina.",
      confLabel: "Sicurezza",
      famLabel: "Somiglianza",
      confHelp: "Quanto i disegni simili sono d'accordo",
      famHelp: "Quanto assomiglia a cio' che ho visto",
      seenCount: "Ho visto",
      seenCats: "gatti",
      seenHouses: "case",
      and: "e",
    },
    lesson: {
      title: "Perché i dati sono importanti",
      p1: "Un'intelligenza artificiale impara solo dagli esempi.",
      p2: "Pochi esempi, o tutti uguali: capisce male.",
      p3: "Tanti esempi diversi: capisce meglio.",
      p4: "Tu sei l'insegnante. I dati sono la lezione.",
    },
    complete: {
      title: "Missione 1 completata",
      body: "Hai insegnato tu a EDO. Senza i tuoi disegni non sapeva niente.",
    },
  },
};

export const DEFAULT_LOCALE = "it";
