export const strings = {
  it: {
    appName: "PixelCraft Academy",
    missionTitle: "Insegna a EDO a riconoscere i miei disegni",
    fakeProfile: "Allievo",
    labels: {
      cat: "GATTO",
      house: "CASA",
      other: "NESSUNO DEI DUE",
      catShort: "gatto",
      houseShort: "casa",
    },
    edo: {
      welcome: "Ciao! Sono EDO. Insegnami i disegni.",
      intro: "Mostrami gatti e case.",
      needMore: "Mi servono altri esempi di",
      askNames: "Che cosa vuoi insegnarmi?",
      namesShort: "Servono due nomi.",
      namesSame: "Devono essere due cose diverse.",
      namesSet: "Bene! Mostrami la prima.",
      ready: "Ho abbastanza esempi. Addestrami!",
      studying: "Studio i tuoi disegni.",
      trained: "Adesso provo a riconoscere.",
      lowConf: "Non sono sicuro… ho visto pochi disegni. Me ne fai vedere altri?",
      highConf: "Ho visto molti più disegni. Riproviamo.",
      guessCat: "Secondo me è un gatto.",
      guessHouse: "Secondo me è una casa.",
      thanks: "Grazie. Imparo da te.",
      cameraNeed: "Mi serve la fotocamera per vedere.",
      drawHint: "Disegna con il dito.",
      learnNow: "Va bene. Lo imparo adesso.",
      addMore: "Ancora qualche disegno, poi riprovo.",
      enough: "Ho gia' tanti disegni di questo tipo.",
      unfamiliar: "Non ho mai visto niente di simile.",
      split: "Alcuni disegni dicono una cosa, altri un'altra.",
      askMore: "Fammene vedere altri e ci riprovo.",
      sameDrawing: "Questo l'ho gia' visto. Provane uno nuovo.",
      betAsk: "Prova a indovinare cosa dico.",
      betRight: "Hai capito come ragiono!",
      betWrong: "Non te lo aspettavi, eh?",
      changedMind: "Ho cambiato idea! Quella foto contava.",
      sameMind: "Dico ancora la stessa cosa.",
      looking2: "Copro un pezzo alla volta e guardo.",
      lookedAt: "Guardavo soprattutto in",
      noWhere: "Non riesco a farlo adesso.",
      noSpot: "Guardavo un po' dappertutto, non un punto solo.",
      focusAsk: "Tocca i quadretti dove devo guardare.",
      focusNone: "Prima scegli almeno un quadretto.",
      focusDone: "Adesso guardo solo li'.",
      whatIsIt: "Allora dimmi che cos'e'.",
      star1: "Prima stella! Ho imparato un po'.",
      star2: "Seconda stella! Più esempi aiutano.",
      star3: "Terza stella! Disegno nuovo riconosciuto.",
      lessonIntro: "Ora ti spiego i dati.",
      noCamera: "Niente fotocamera. Scatta o disegna.",
      looking: "Guardo il disegno…",
      complete: "Missione finita. Sei tu l'insegnante.",
    },
    ui: {
      start: "Inizia",
      continue: "Continua",
      back: "Indietro",
      train: "Addestra",
      retrain: "Addestra di nuovo",
      test: "Prova EDO",
      addDrawings: "Aggiungi disegni",
      photograph: "Fotografa",
      draw: "Disegna",
      sample: "Disegno di prova",
      save: "Salva",
      cancel: "Annulla",
      clear: "Cancella",
      shutter: "Scatta",
      cameraOk: "Va bene",
      yesCat: "Sì, è un GATTO",
      yesHouse: "Sì, è una CASA",
      noCat: "No, è un GATTO",
      noHouse: "No, è una CASA",
      seeLesson: "Perché i dati sono importanti",
      finish: "Ho capito",
      speak: "Ascolta EDO",
      countOf: "di",
      loading: "EDO si prepara…",
      pickLabel: "Tocca GATTO o CASA, poi aggiungi un disegno.",
      needThree: "Servono almeno 3 gatti e 3 case.",
      goalTen: "Arriviamo a 10 per ciascuno.",
      permissionBody:
        "EDO ha bisogno della fotocamera per vedere i tuoi disegni. Le foto restano sul telefono.",
      emptySlot: "Nessun esempio ancora",
      neither: "NESSUNO",
      testHint: "Mostra un disegno. EDO prova a dire che cos'è.",
      newDrawing: "Usa un disegno nuovo, mai fotografato.",
      bootError: "Non riesco a caricare il cervello di EDO. Ricarica la pagina.",
      confLabel: "Sicurezza",
      famLabel: "Somiglianza",
      confHelp: "Quanto i disegni simili sono d'accordo",
      famHelp: "Quanto assomiglia a cio' che ho visto",
      seenCount: "Ho visto",
      seenCats: "gatti",
      seenHouses: "case",
      seenOther: "altre cose",
      and: "e",
      otherTitle: "ALTRO",
      otherHint: "Cose che non sono ne\u0027 gatti ne\u0027 case.",
      yesRight: "Si\u0027, e\u0027 giusto",
      noItIs: "No, e\u0027",
      outOf: "su",
      sayThis: "dicono",
    },
    lesson: {
      title: "Perché i dati sono importanti",
      p1: "Un'intelligenza artificiale impara solo dagli esempi.",
      p2: "Pochi esempi, o tutti uguali: capisce male.",
      p3: "Tanti esempi diversi: capisce meglio.",
      p4: "Tu sei l'insegnante. I dati sono la lezione.",
    },
    complete: {
      title: "Missione 1 completata",
      body: "Hai insegnato tu a EDO. Senza i tuoi disegni non sapeva niente.",
    },
  },
};

export const DEFAULT_LOCALE = "it";
